services:
  backend:
    build:
      context: ../nodejs
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
    - ./videos:/usr/src/app/videos
    networks:
      - capt_direct_net
    environment:
      NODE_ENV: development
    depends_on:
      - database
      - redis
      - hls_service

  hls_service:
    build: 
      context: ../hls_service
    container_name: hls_service
    ports:
      - "5000:5000"
    networks:
      - capt_direct_net
    volumes:
      - ./hls_output:/usr/src/app/hls_output
      - ./nginx/hls_output:/opt/data/hls
      - ./videos:/usr/src/app/videos

  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5433:5432"
    networks:
      - capt_direct_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kh@didia74
      POSTGRES_DB: stc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379" # Corrected format for ports
    networks:
      - capt_direct_net
networks:
  capt_direct_net:
    driver: bridge

volumes:
  postgres_data:
